- name: Install binaries on controllers
  hosts: controllers
  become: yes
  tasks:
    - name: show ipv4
      debug: var=ansible_default_ipv4.address
    - name: Download Kubernetes api-server
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kube-apiserver
        dest: /usr/local/bin/
    - name: Download Kubernetes api-controller-manager
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kube-controller-manager
        dest: /usr/local/bin/
    - name: Download Kubernetes api-scheduler
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kube-scheduler
        dest: /usr/local/bin/
    - name: Download Kubernetes kubectl
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/

    - name: make kubernetes binaries executable
      shell: chmod +x /usr/local/bin/kube*
    - name: make directory varlibkubernetes
      shell: mkdir -p /var/lib/kubernetes
