- name: Health check
  hosts: etcd
  become: yes
  tasks:
    - name: etcdctl check health
      shell: etcdctl endpoint health --endpoints=https://etcd-0:2379 --cacert=/etc/etcd/ca.crt --cert=/etc/etcd/etcd.crt --key=/etc/etcd/etcd.key
      register: health
      become: yes
    - name: output
      debug: var=health
