- name: Enable services
  hosts: nodes
  become: yes
  tasks:
    - name: reload systemd service
      ansible.builtin.systemd:
        name: containerd.service
        daemon_reload: yes
        state: started
    - name: reload systemd service
      ansible.builtin.systemd:
        name: kubelet.service
        daemon_reload: yes
        state: started
    - name: reload systemd service
      ansible.builtin.systemd:
        name: kube-proxy.service
        daemon_reload: yes
        state: started

