- name: Install binaries on worker nodes
  hosts: nodes
  become: yes
  tasks:

    - name: Create Directory Set
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
          - /etc/cni/net.d
          - /opt/cni/bin
          - /var/lib/kubelet
          - /var/lib/kube-proxy
          - /var/lib/kubernetes
          - /var/run/kubenetes
          - /usr/src/containerd
          - /etc/containerd

    - name: untar crictl
      shell: tar -xvf /usr/src/crictl-v1.21.0-linux-amd64.tar.gz -C /usr/src
    - name: untar containerd
      shell: tar -xvf /usr/src/containerd-1.4.4-linux-amd64.tar.gz -C /usr/src/containerd
    - name: untar cni-plugins
      shell: tar -xvf /usr/src/cni-plugins-linux-amd64-v0.9.1.tgz -C /opt/cni/bin/
    - name: move runc minus arch
      shell: mv /usr/src/runc.amd64 /usr/src/runc
    - name: set executable permissions
      shell: cd /usr/src/;chmod +x crictl kubectl kube-proxy kubelet runc
    - name: move binaries to PATH logical location /usr/local/bin 
      shell: cd /usr/src/;cp -pr crictl kubectl kube-proxy kubelet runc /usr/local/bin/
    - name: move containerd binary
      shell: cp -pr /usr/src/containerd/bin/* /bin/
     
