- name: Configure node worker
  hosts: nodes
  become: yes
  tasks:

    - name: Copy kubelet config script
      ansible.builtin.copy:
        src: files/kubelet.sh
        dest: /var/lib/kubernetes/
    - name: Copy kube-proxy config script
      ansible.builtin.copy:
        src: files/kube-proxy.sh
        dest: /var/lib/kubernetes/


    - name: Copy 10-bridge.conf
      ansible.builtin.copy:
        src: files/10-bridge.conf
        dest: /etc/cni/net.d/10-bridge.conf

    - name: Copy 99-loopback.conf
      ansible.builtin.copy:
        src: files/99-loopback.conf
        dest: /etc/cni/net.d/99-loopback.conf

    - name: Copy containerd toml config
      ansible.builtin.copy:
        src: files/containerd/config.toml
        dest: /etc/containerd/config.toml

    - name: Copy containerd systemd service
      ansible.builtin.copy:
        src: files/containerd.service
        dest: /etc/systemd/system/containerd.service

    - name: Copy kubelet systemd service
      ansible.builtin.copy:
        src: files/kubelet.service
        dest: /etc/systemd/system/kubelet.service

    - name: Copy kubelet config
      ansible.builtin.copy:
        src: files/kubelet-config.yaml
        dest: /var/lib/kubelet/kubelet-config.yaml

    - name: Copy kube-proxy config
      ansible.builtin.copy:
        src: files/kube-proxy-config.yaml
        dest: /var/lib/kube-proxy/kube-proxy-config.yaml

    - name: Copy kube-proxy systemd service
      ansible.builtin.copy:
        src: files/kube-proxy.service
        dest: /etc/systemd/system/kube-proxy.service

    - name: REGEX Internal IP for kubelet config script
      ansible.builtin.replace:
        path: /var/lib/kubernetes/kubelet.sh
        regexp: 'INTERNAL_IP'
        replace: 'controller-0'
    - name: REGEX Internal IP for kube-proxy config script
      ansible.builtin.replace:
        path: /var/lib/kubernetes/kube-proxy.sh
        regexp: 'INTERNAL_IP'
        replace: 'controller-0'



    - name: Create kubeconfig for kubelet
      shell: sh /var/lib/kubernetes/kubelet.sh

    - name: Create kubeconfig for kube-proxy
      shell: sh /var/lib/kubernetes/kube-proxy.sh
 
